//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Discovery.rc
// Ported to Windows 8.1 by Fulcrum.013 Mariupol, Ukraine 
// 17 september 2020
//
#define IDD_ABOUTBOX                    100
#define IDC_TRACKROTXY                  102
#define IDC_TRACKROTZ                   103
#define IDC_TRACKSHIFT                  104
#define IDC_TRACKZOOM                   105
#define IDC_TRACKROTXY_A                106
#define IDC_TRACKROTZ_A                 107
#define IDC_TRACKSHIFT_A                108
#define IDC_TRACKZOOM_A                 109
#define IDC_SLABMODE                    110
#define IDR_MAINFRAME                   128
#define IDR_DISCOVTYPE                  129
#define IDS_OPENFILTER                  129
#define IDR_REPORT_HEADER               130
#define IDS_SAVELISTFILTER              130
#define IDR_REPORT_LIST                 131
#define IDS_REPORT_VIEW_OF              131
#define IDS_PAGE_X_OF_X                 132
#define IDR_QSD                         132
#define IDS_UNKNOWN_FILE_FORMAT         133
#define IDR_REPORT                      133
#define IDS_LOAD_ERROR                  134
#define IDR_CHEMISTRY                   134
#define IDR_STATISTICS                  135
#define IDS_RUN_QSD_SHEET_TITLE         135
#define IDD_QSD_SELECT_RUN              136
#define IDS_NO_ERROR                    136
#define IDD_QSD_SINGLE_RUN              137
#define IDS_GENERIC_ERROR               137
#define IDD_QSD_MULTIPLE_RUN            138
#define IDS_FILE_NOT_FOUND              138
#define IDS_BAD_PATH                    139
#define IDD_QSD_CONFIGURATION           139
#define IDS_TOO_MANY_OPEN_FILES         140
#define IDD_QSD_PROGRESS                140
#define IDS_ACCESS_DENIED               141
#define IDI_RED                         141
#define IDS_REMOVE_CURRENT_DIR          142
#define IDI_BLUE                        142
#define IDS_DIRECTORY_FULL              143
#define IDI_GREEN                       143
#define IDS_BAD_SEEK                    144
#define IDI_PURPLE                      144
#define IDS_HARD_IO                     145
#define IDI_CYAN                        145
#define IDS_SHARING_VIOLATION           146
#define IDI_YELLOW                      146
#define IDS_LOCK_VIOLATION              147
#define IDI_LIGHT_RED                   147
#define IDS_DISK_FULL                   148
#define IDI_LIGHT_BLUE                  148
#define IDS_END_OF_FILE                 149
#define IDS_UNKNOWN_FILE_ERROR          150
#define IDS_COULD_NOT_READ_ALL_PROPERTIES 151
#define IDR_PROFILE_LIST                151
#define IDS_CSV_NEED_AT_LEAST_THREE_COLUMNS 152
#define IDD_QSD_CONF_SINGLE             152
#define IDS_CSV_FIRST_COLUMN_NOT_STOICHIOMETRY 153
#define IDR_QSD_GRAPH                   153
#define IDS_SUM                         154
#define IDR_QSD_LIST                    154
#define IDS_DIFFERENCE                  155
#define IDB_SLABWARN                    155
#define IDS_RATIO                       156
#define IDB_SLABWARN_OLD                156
#define IDR_QSD_HISTO                   156
#define IDS_PRODUCT                     157
#define IDR_TRASH                       157
#define IDS_MAXIMUM                     158
#define IDD_QSD_IMPORT                  158
#define IDS_RUN_X_OF_Y_BEST_RESULT_PERCENT 159
#define IDS_PREPARING_DATA              160
#define IDS_ANALYZING_DATA              161
#define IDS_QSD_RUN_CANCELED            162
#define IDS_QSD_CANNOT_READ_PROFILES    163
#define IDS_QSD_CANNOT_READ_RESULTS     164
#define IDS_QSD_CANNOT_READ_DISCOVERYSPACE 165
#define IDS_NOOPERATION                 166
#define IDS_NEED_2D_PROJ_FOR_SLAB       167
#define IDS_CANNOT_CREATE_CSV_FILE_XXX  168
#define IDS_INITIALIZING                169
#define IDS_RUN_X_OF_Y                  170
#define IDS_PRODUCT2                    171
#define IDS_MINIMUM                     172
#define IDC_SINGLE                      1000
#define IDC_RADIO2                      1001
#define IDC_PROP_X                      1002
#define IDC_PROP_Y                      1003
#define IDC_PROP_Z                      1004
#define IDC_OP_X                        1005
#define IDC_OP_Y                        1006
#define IDC_PROP                        1006
#define IDC_OP_Z                        1007
#define IDC_OP                          1007
#define IDC_RUNS                        1008
#define IDC_ALL                         1009
#define IDC_NUM                         1010
#define IDC_MAX                         1011
#define IDC_ERROR                       1012
#define IDC_SPIN1                       1013
#define IDC_SPIN2                       1014
#define IDC_PROGRESS                    1015
#define IDC_QUALITY                     1015
#define IDC_WHAT                        1016
#define IDC_SPIN3                       1016
#define IDC_RESULT                      1017
#define IDC_LEVEL1                      1018
#define IDC_TYPE1                       1019
#define IDC_RADIO3                      1020
#define IDC_RADIO4                      1021
#define IDC_RADIO5                      1022
#define IDC_LOAD                        1023
#define IDC_FILENAME                    1024
#define IDC_STATUS                      1025
#define ID_VIEW_QSD                     32771
#define ID_VIEW_REPORT                  32772
#define ID_EDIT_SELECT_INV              32773
#define ID_EDIT_SELECT_COLUMN           32774
#define ID_REPORT_SELECT_COLUMN         32775
#define ID_REPORT_SORT_ASC              32776
#define ID_REPORT_SORT_DESC             32777
#define ID_REPORT_SORT_NO               32778
#define ID_FILE_SAVE_DATA               32779
#define ID_QSD_START                    32780
#define ID_REPORT_OPTIONS               32781
#define ID_CHEM_OPTIONS                 32782
#define ID_STAT_OPTIONS                 32783
#define ID_VIEW_CHEMISTRY               32784
#define ID_QSD_OPTIONS                  32787
#define ID_VIEW_STATISTICS              32788
#define ID_QSD_STOP                     32789
#define ID_QSD_START_SINGLE             32790
#define ID_VIEW_QSD_PROFILE             32792
#define ID_VIEW_QSD_CUBE                32793
#define ID_VIEW_QSD_ADJUST              32794
#define ID_VIEW_QSD_PROJ_XY             32795
#define ID_VIEW_QSD_PROJ_XZ             32796
#define ID_VIEW_QSD_PROJ_YZ             32797
#define ID_VIEW_QSD_DOTS                32798
#define ID_VIEW_QSD_BALLS               32799
#define ID_VIEW_ROTXY                   32800
#define ID_VIEW_ROTZ                    32801
#define ID_VIEW_SHIFT                   32802
#define ID_VIEW_ENLARGE                 32803
#define ID_VIEW_NOTRACK                 32804
#define ID_VIEW_QSD_GRID                32805
#define ID_VIEW_QSD_PROJ_CLOSEST        32806
#define ID_VIEW_QSD_SLAB                32807
#define ID_VIEW_QSD_NO_SLAB             32808
#define ID_VIEW_QSD_HISTO_FULL          32809
#define ID_VIEW_QSD_HISTO_ZOOM          32810
#define ID_INDICATOR_COUNT              32811
#define ID_INDICATOR_SEL                32812
#define ID_QSD_START_DIRECT             32990

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
